// auth types
export const SET_THEME = "SET_THEME";

// materials types
export const MATERIALS_LIST_REQ = "MATERIALS_LIST_REQ";
export const MATERIALS_LIST_SUCCESS = "MATERIALS_LIST_SUCCESS";
export const MATERIALS_LIST_ERROR = "MATERIALS_LIST_ERROR";

export const MATERIALS_SINGLE_REQ = "MATERIALS_SINGLE_REQ";
export const MATERIALS_SINGLE_SUCCESS = "MATERIALS_SINGLE_SUCCESS";
export const MATERIALS_SINGLE_ERROR = "MATERIALS_SINGLE_ERROR";
